version: "3.9"

services:
  discord-bot:
    build: ./discord-bot
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - discord_data:/app
    command: node index.js

volumes:
  discord_data:
